fruits = {
    "apple" : 130,
    "avocado" : 50,
    "avocado california":50,
    "banana":110,
    "cantaloupe":50,
    "grapefruit":60,
    "grapes":90,
    "honeydew melon":50,
    "kiwifruit":90,
    "lemon":15,
    "lime":20,
    "nectarine":60,
    "orange":80,
    "peach":60,
    "pear":100,
    "pineapple":50,
    "plums":70,
    "strawberries":50,
    "sweet cherries":100,
    "tangerine":50,
    "watermelon":80
}

def main():
    print(fruit_to_calories(input("Input: ").strip()), end = "")


def fruit_to_calories(answer):
    # The current sent info in the test script is appple not Apple
    # So I am lowercasing the keys in the dict.
    # Aand using is to .lower() all keys and .lower() all incoming data
    # Test code is wrong
    # Results for cs50/problems/2022/python/nutrition generated by check50 v3.3.8
    # :) nutrition.py exists
    # :( input of apple yields output of 130
    #     expected "130", not ""
    # :) input of Avocado yields output of 50
    # :) input of Kiwifruit yields output of 90
    # :( input of pear yields output of 100
    #     expected "100", not ""
    # :) input of Sweet Cherries yields output of 100
    # :) nutrition.py ignores invalid input

    if answer.lower() in fruits:
        return "Calories: ", fruits[answer.lower()]
    else:
        return ""
main()